import { supabase } from "@/integrations/supabase/client";
import type { Database, Json } from "@/integrations/supabase/types";
import { PIIRedactor } from "./piiRedactor";

export interface AIExplanationRequest {
  question: string;
  workspaceId?: string;
  context: {
    taxType?: string;
    calculationType?: string;
    values?: Record<string, unknown>;
    ruleVersion?: string;
  };
}

export interface AIExplanationResponse {
  answer: string;
  isStubbed: boolean;
  explanationId?: string;
}

type ExplanationContext = AIExplanationRequest["context"];
type ExplanationInsert = Database["public"]["Tables"]["explanations"]["Insert"];
type ExplanationRow = Database["public"]["Tables"]["explanations"]["Row"];

function toJsonValue(value: ExplanationContext): Json {
  return value as unknown as Json;
}

function toContextRecord(value: Json | null): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  return value as Record<string, unknown>;
}

/**
 * Invokes the 'ai-chat' Supabase Edge Function with PII-sanitized context
 */
export async function getExplanation(request: AIExplanationRequest): Promise<AIExplanationResponse> {
  const { question, context, workspaceId } = request;

  try {
    const { data: { user } } = await supabase.auth.getUser();

    if (!workspaceId) {
      throw new Error("An active workspace is required for AI explanations.");
    }

    // 1. Sanitize the payload to ensure no PII leaks to OpenAI
    const sanitizedContext = PIIRedactor.sanitizePayload(context) as ExplanationContext;

    // 2. Format the message chain
    const messages = [
      {
        role: "user",
        content: `I am looking at a ${sanitizedContext.taxType || 'tax'} calculation.
Context Data: ${JSON.stringify(sanitizedContext.values || {})}

My Question: ${question}`
      }
    ];

    // 3. Invoke the Edge Function securely
    const { data, error } = await supabase.functions.invoke('ai-chat', {
      body: { messages, stream: false, workspaceId }
    });

    if (error) {
      console.error("AI Edge Function Error:", error);
      throw new Error("Unable to connect to the Buoyance AI Engine.");
    }

    let answer = data?.content || "No explanation available.";

    // Add legal guardrail notice
    answer += `\n\n---\n*Note: This explanation is generated by AI for informational purposes only under the NTA 2025 framework. It does not alter your statutory calculated tax amounts or constitute formal legal advice.*`;

    // 4. Log the prompt & response immutably
    let explanationId: string | undefined;
    if (user) {
      const explanationToInsert: ExplanationInsert = {
        user_id: user.id,
        question,
        answer,
        context: toJsonValue(sanitizedContext),
      };

      const { data: logData } = await supabase
        .from("explanations")
        .insert(explanationToInsert)
        .select("id")
        .single();

      explanationId = logData?.id;
    }

    return {
      answer,
      isStubbed: false, // We are now live
      explanationId,
    };

  } catch (err: unknown) {
    console.error("Failed to generate AI explanation:", err);
    return {
      answer: "The Buoyance AI Engine is currently unavailable or unreachable. Please verify your connection or check whether you have sufficient AI Query quota remaining in your workspace.",
      isStubbed: true,
    };
  }
}

/**
 * Get explanation history for the current user
 */
export async function getExplanationHistory(limit = 20): Promise<Array<{
  id: string;
  question: string;
  answer: string;
  context: Record<string, unknown>;
  created_at: string;
}>> {
  const { data, error } = await supabase
    .from("explanations")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) {
    console.error("Failed to fetch explanation history:", error);
    return [];
  }

  return (data || []).map((row: ExplanationRow) => ({
    id: row.id,
    question: row.question,
    answer: row.answer,
    context: toContextRecord(row.context),
    created_at: row.created_at || "",
  }));
}
